---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Export kubeconfigpath
      become: true
      blockinfile:
        path: /root/.bash_profile
        block: |
          export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
      register: kubepath
    - debug: var=kubepath
    - name: Save Path in root
      become: true
      shell: source /root/.bash_profile
      register: exportkube
    - debug: var=exportkube
    - name: Generate manifest for new tls-ca secret from new cacerts.pem file and save it to output yaml file.
      shell: kubectl -n cattle-system create secret generic tls-ca --from-file=/root/cacerts.pem   --dry-run --save-config -o yaml | kubectl apply -f -
      regitser: tls_ca
    - name: Generate manifest for new  tls-rancher-ingress secret from new  tls.key & tls.crt files and save it to output yaml file.
      shell: kubectl -n cattle-system create secret tls tls-rancher-ingress   --cert=/root/tls.crt   --key=/root/tls.key   --dry-run --save-config -o yaml | kubectl apply -f -
      register: tls_rancher
    - name: Upgrade the Helm application instance using the original configuration values
      shell: helm upgrade rancher rancher-stable/rancher --namespace cattle-system --set hostname=”{{hostname}}” --set ingress.tls.source=secret --set privateCA=true --version=2.5.9
      register: helm_upgrade
