---
- hosts: webservers
  remote_user: root
  gather_facts: False
  tasks:
  - name: running command
    command: date
    register: git
  - debug: var=git.stdout
  
  - name: copying files
    copy:
      content: "{{git}}"
      dest: /root/gitout.txt
