---
- hosts: 127.0.0.1
  remote_user: root
  gather_facts: False
  tasks:
  - name: running command
    command: date
    register: gitout
  - debug: var=gitout.stdout
  
  - name: copying files
    copy:
      content: "{{gitout}}"
      dest: /root/gitout1.txt
