---
- hosts: webservers
  remote_user: root
  gather_facts: False
  tasks:
  - name: running command
    command: date
    register: gitout
  - debug: var=gitout.stdout
  
  - name: copying files
    copy:
      content: "{{gitout}}"
      dest: /root/gitout2.txt
